# Generated by Django 2.0.7 on 2020-08-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.TextField(default='this is cool!'),
        ),
    ]
